### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by santiagopuentep** [krthush/link-preview#6]
The demo fails to return any results, showing a 503 (Service Unavailable) error.

**Comment by santiagopuentep** [comment]
Running on localhost throws "Request failed with status code 400".

**Comment by santiagopuentep** [comment]
I added `http://` to the URL in localhost and it worked (no more 400), the online demo is still failing.

**Comment by krthush** [comment]
should be fixed now with the recent commits, at least there shouldnt be any more crashes and the project should run fine  - but I do think the stealth package we use here https://www.npmjs.com/package/puppeteer-extra-plugin-stealth is now outdated so performance of getting link previews not as good any more

**Comment by krthush** [comment]
@santiagopuentep feel free to look at #7 if you'd like to improve the results!
