### ISSUE TITLE
Cannot read properties of undefined (reading 'title')

### ISSUE THREAD

**Issue by santiagopuentep** [krthush/link-preview#8]
https://twiter.com (wrong website, with a single "t") fails with the Cannot read properties of undefined (reading 'title') at getLinkPreview (LinkPreview.tsx:28:43).

**Comment by santiagopuentep** [comment]
Same with:
- https://twitter.com/JMilei/status/1780299208949477490
- https://www.liberalstudies.ca/wp-content/uploads/2014/11/Economics-in-One-Lesson_2.pdf (A file).

**Comment by krthush** [comment]
The project currently doesn't support spelling errors with URLs or generating image previews for files

4855f985dc995f53148d520d79d8a9e1c98d4d6e allows you to get https://twitter.com/JMilei/status/1780299208949477490

**Comment by santiagopuentep** [comment]
A spelling error is just a website that doesn't return an HTML. I think it should return an error for that, instead of an undefined property access exception, otherwise it's not gracefully solving errors. Also, in the demo, if the website doesn't have ab https:// or another error is returned, I think it should show the error message or something, otherwise it looks like the demo is broken or that it doesn't work with many URLs. That's what I thought at first before coming back to the article later.

Thanks for such quick changes 👌
